# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - scorepredict

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cloudprojectfinal/
        username: ${{ secrets.AzureAppService_ContainerUsername_84033c3043394fa5b83627b05c8716d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a2133d5d6d94c00baa7c62243ce43ea }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cloudprojectfinal/${{ secrets.AzureAppService_ContainerUsername_84033c3043394fa5b83627b05c8716d5 }}/scorepredict:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scorepredict'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b06dfcbfdab244518371a13fa1bff8b6 }}
        images: 'cloudprojectfinal/${{ secrets.AzureAppService_ContainerUsername_84033c3043394fa5b83627b05c8716d5 }}/scorepredict:${{ github.sha }}'